# Import libs & Data

In [1]:
import polars as pl
import polars.selectors as cs

In [2]:
# inference_res = pl.read_parquet(
#     "../../results/inference/pipeline_results_20251006_144126.parquet"
# )

res_df = pl.read_csv("../../results/evaluation/veatic_per_video_20251006_144126.csv")

In [3]:
len(res_df.columns)

38

In [4]:
mae_df = (
    res_df.select("video_id", "Stablization", cs.starts_with("mae"))
    .unpivot(
        index=["video_id", "Stablization"],
        variable_name="metrics",
        value_name="mae",
        on=cs.starts_with("mae"),
    )
    .sort("video_id")
)

with pl.Config(set_tbl_rows=20):
    display(mae_df.head(20))

shape: (20, 4)
┌──────────┬──────────────┬────────────────────┬──────────┐
│ video_id ┆ Stablization ┆ metrics            ┆ mae      │
│ ---      ┆ ---          ┆ ---                ┆ ---      │
│ i64      ┆ bool         ┆ str                ┆ f64      │
╞══════════╪══════════════╪════════════════════╪══════════╡
│ 0        ┆ false        ┆ mae_scene_valence  ┆ 0.0068   │
│ 0        ┆ true         ┆ mae_scene_valence  ┆ 0.017317 │
│ 0        ┆ false        ┆ mae_scene_arousal  ┆ 0.230319 │
│ 0        ┆ true         ┆ mae_scene_arousal  ┆ 0.243394 │
│ 0        ┆ false        ┆ mae_face_valence   ┆ 0.037123 │
│ 0        ┆ true         ┆ mae_face_valence   ┆ 0.036581 │
│ 0        ┆ false        ┆ mae_face_arousal   ┆ 0.201124 │
│ 0        ┆ true         ┆ mae_face_arousal   ┆ 0.204232 │
│ 0        ┆ false        ┆ mae_fusion_valence ┆ 0.02229  │
│ 0        ┆ true         ┆ mae_fusion_valence ┆ 0.037298 │
│ 0        ┆ false        ┆ mae_fusion_arousal ┆ 0.189869 │
│ 0        ┆ true         ┆ mae_fusion_arousal ┆ 0.20616  │
│ 1        ┆ false        ┆ mae_scene_valence  ┆ 0.072854 │
│ 1        ┆ true         ┆ mae_scene_valence  ┆ 0.080572 │
│ 1        ┆ false        ┆ mae_scene_arousal  ┆ 0.16884  │
│ 1        ┆ true         ┆ mae_scene_arousal  ┆ 0.152485 │
│ 1        ┆ false        ┆ mae_face_valence   ┆ 0.219579 │
│ 1        ┆ true         ┆ mae_face_valence   ┆ 0.219722 │
│ 1        ┆ false        ┆ mae_face_arousal   ┆ 0.137744 │
│ 1        ┆ true         ┆ mae_face_arousal   ┆ 0.139669 │
└──────────┴──────────────┴────────────────────┴──────────┘

In [5]:
with pl.Config(set_tbl_rows=20):
    display(
        mae_df.group_by(["metrics", "Stablization"])
        .agg(pl.mean("mae").alias("mae_mean"))
        .sort(["metrics", "Stablization"])
        .pivot(index="metrics", on="Stablization", values="mae_mean")
    )

shape: (6, 3)
┌────────────────────┬──────────┬──────────┐
│ metrics            ┆ false    ┆ true     │
│ ---                ┆ ---      ┆ ---      │
│ str                ┆ f64      ┆ f64      │
╞════════════════════╪══════════╪══════════╡
│ mae_face_arousal   ┆ 0.167998 ┆ 0.168111 │
│ mae_face_valence   ┆ 0.208533 ┆ 0.208359 │
│ mae_fusion_arousal ┆ 0.160549 ┆ 0.160829 │
│ mae_fusion_valence ┆ 0.193418 ┆ 0.19286  │
│ mae_scene_arousal  ┆ 0.203031 ┆ 0.203255 │
│ mae_scene_valence  ┆ 0.239088 ┆ 0.238353 │
└────────────────────┴──────────┴──────────┘

# Potential way to compare results

The task is to select a sample of videos for the front-end. It's not a random selection, so I'm thinking how should we go about segmenting the videos? We can choose 3? Where?

- Stabilizer: Enabled vs Disabled. Even though Fusion Mae is the same, but what about the viewer's perspective? Maybe across a sample of 10 videos, is the music tune better with or without stabilizer? 
- face_coverage: when `face_coverage` is high and `face_coverage` is low, does that make a difference?

# Stabilizer: Enabled vs Disabled.

In [6]:
res_df

shape: (248, 38)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ video_id ┆ Stablizat ┆ gt_mean_v ┆ gt_mean_a ┆ … ┆ delta_mae ┆ delta_mae ┆ delta_mae ┆ export_ti │
│ ---      ┆ ion       ┆ alence    ┆ rousal    ┆   ┆ _face_aro ┆ _fusion_v ┆ _fusion_a ┆ mestamp   │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ usal      ┆ alence    ┆ rousal    ┆ ---       │
│          ┆ bool      ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ false     ┆ -0.063334 ┆ -0.258307 ┆ … ┆ 0.003108  ┆ 0.015008  ┆ 0.016291  ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 0        ┆ true      ┆ -0.063334 ┆ -0.258307 ┆ … ┆ 0.003108  ┆ 0.015008  ┆ 0.016291  ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 1        ┆ false     ┆ -0.003551 ┆ 0.137104  ┆ … ┆ 0.001925  ┆ -0.025176 ┆ -0.009981 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 1        ┆ true      ┆ -0.003551 ┆ 0.137104  ┆ … ┆ 0.001925  ┆ -0.025176 ┆ -0.009981 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 10       ┆ false     ┆ -0.384963 ┆ 0.146455  ┆ … ┆ 0.000464  ┆ 0.015137  ┆ 0.020322  ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 97       ┆ true      ┆ 0.2349    ┆ -0.047971 ┆ … ┆ 0.001015  ┆ 0.033614  ┆ 0.001661  ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 98       ┆ false     ┆ 0.143648  ┆ 0.069885  ┆ … ┆ -0.000156 ┆ -0.003265 ┆ -0.008395 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 98       ┆ true      ┆ 0.143648  ┆ 0.069885  ┆ … ┆ -0.000156 ┆ -0.003265 ┆ -0.008395 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 99       ┆ false     ┆ -0.051907 ┆ 0.112368  ┆ … ┆ 0.00056   ┆ -0.014645 ┆ -0.006422 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
│ 99       ┆ true      ┆ -0.051907 ┆ 0.112368  ┆ … ┆ 0.00056   ┆ -0.014645 ┆ -0.006422 ┆ 20251006_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 144126    │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Video Selection: Lowest Valence MAE

In [7]:
face_valence_top = (
    res_df.filter(
        (pl.col("mae_face_valence") < pl.col("mae_scene_valence"))
        & (pl.col("mae_face_valence") < pl.col("mae_fusion_valence"))
    )
    .sort("mae_face_valence")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_face_valence")
    .select(
        "video_id",
        "Stablization",
        "mae_face_valence",
        "mae_scene_valence",
        "mae_fusion_valence",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

scene_valence_top = (
    res_df.filter(
        (pl.col("mae_scene_valence") < pl.col("mae_face_valence"))
        & (pl.col("mae_scene_valence") < pl.col("mae_fusion_valence"))
    )
    .sort("mae_scene_valence")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_scene_valence")
    .select(
        "video_id",
        "Stablization",
        "mae_scene_valence",
        "mae_face_valence",
        "mae_fusion_valence",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

fusion_valence_top = (
    res_df.filter(
        (pl.col("mae_fusion_valence") < pl.col("mae_scene_valence"))
        & (pl.col("mae_fusion_valence") < pl.col("mae_face_valence"))
    )
    .sort("mae_fusion_valence")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_fusion_valence")
    .select(
        "video_id",
        "Stablization",
        "mae_fusion_valence",
        "mae_scene_valence",
        "mae_face_valence",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

with pl.Config(set_tbl_rows=10):
    print("3 videos with lowest face_valence MAE"), display(face_valence_top)
    print("3 videos with lowest scene_valence MAE"), display(scene_valence_top)
    print("3 videos with lowest fusion_valence MAE"), display(fusion_valence_top)

3 videos with lowest face_valence MAE

shape: (3, 5)
┌──────────┬──────────────┬──────────────────┬───────────────────┬────────────────────┐
│ video_id ┆ Stablization ┆ mae_face_valence ┆ mae_scene_valence ┆ mae_fusion_valence │
│ ---      ┆ ---          ┆ ---              ┆ ---               ┆ ---                │
│ i64      ┆ bool         ┆ f64              ┆ f64               ┆ f64                │
╞══════════╪══════════════╪══════════════════╪═══════════════════╪════════════════════╡
│ 42       ┆ true         ┆ 0.0053           ┆ 0.236             ┆ 0.0683             │
│ 46       ┆ false        ┆ 0.0106           ┆ 0.0463            ┆ 0.0107             │
│ 53       ┆ false        ┆ 0.0124           ┆ 0.0179            ┆ 0.0197             │
└──────────┴──────────────┴──────────────────┴───────────────────┴────────────────────┘

3 videos with lowest scene_valence MAE

shape: (3, 5)
┌──────────┬──────────────┬───────────────────┬──────────────────┬────────────────────┐
│ video_id ┆ Stablization ┆ mae_scene_valence ┆ mae_face_valence ┆ mae_fusion_valence │
│ ---      ┆ ---          ┆ ---               ┆ ---              ┆ ---                │
│ i64      ┆ bool         ┆ f64               ┆ f64              ┆ f64                │
╞══════════╪══════════════╪═══════════════════╪══════════════════╪════════════════════╡
│ 120      ┆ true         ┆ 0.0022            ┆ 0.189            ┆ 0.1221             │
│ 86       ┆ true         ┆ 0.0058            ┆ 0.2443           ┆ 0.0768             │
│ 0        ┆ false        ┆ 0.0068            ┆ 0.0371           ┆ 0.0223             │
└──────────┴──────────────┴───────────────────┴──────────────────┴────────────────────┘

3 videos with lowest fusion_valence MAE

shape: (3, 5)
┌──────────┬──────────────┬────────────────────┬───────────────────┬──────────────────┐
│ video_id ┆ Stablization ┆ mae_fusion_valence ┆ mae_scene_valence ┆ mae_face_valence │
│ ---      ┆ ---          ┆ ---                ┆ ---               ┆ ---              │
│ i64      ┆ bool         ┆ f64                ┆ f64               ┆ f64              │
╞══════════╪══════════════╪════════════════════╪═══════════════════╪══════════════════╡
│ 40       ┆ true         ┆ 0.0002             ┆ 0.1632            ┆ 0.0921           │
│ 49       ┆ false        ┆ 0.0005             ┆ 0.0123            ┆ 0.0238           │
│ 51       ┆ false        ┆ 0.0016             ┆ 0.2549            ┆ 0.1073           │
└──────────┴──────────────┴────────────────────┴───────────────────┴──────────────────┘

In [8]:
face_arousal_top = (
    res_df.filter(
        (pl.col("mae_face_arousal") < pl.col("mae_scene_arousal"))
        & (pl.col("mae_face_arousal") < pl.col("mae_fusion_arousal"))
    )
    .sort("mae_face_arousal")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_face_arousal")
    .select(
        "video_id",
        "Stablization",
        "mae_face_arousal",
        "mae_scene_arousal",
        "mae_fusion_arousal",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

scene_arousal_top = (
    res_df.filter(
        (pl.col("mae_scene_arousal") < pl.col("mae_face_arousal"))
        & (pl.col("mae_scene_arousal") < pl.col("mae_fusion_arousal"))
    )
    .sort("mae_scene_arousal")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_scene_arousal")
    .select(
        "video_id",
        "Stablization",
        "mae_scene_arousal",
        "mae_face_arousal",
        "mae_fusion_arousal",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

fusion_arousal_top = (
    res_df.filter(
        (pl.col("mae_fusion_arousal") < pl.col("mae_scene_arousal"))
        & (pl.col("mae_fusion_arousal") < pl.col("mae_face_arousal"))
    )
    .sort("mae_fusion_arousal")
    .unique(subset=["video_id"], keep="first")
    .sort("mae_fusion_arousal")
    .select(
        "video_id",
        "Stablization",
        "mae_fusion_arousal",
        "mae_scene_arousal",
        "mae_face_arousal",
    )
    .with_columns(cs.starts_with("mae_").round(4))
    .head(3)
)

with pl.Config(set_tbl_rows=10):
    print("3 videos with lowest face_arousal MAE"), display(face_arousal_top)
    print("3 videos with lowest scene_arousal MAE"), display(scene_arousal_top)
    print("3 videos with lowest fusion_arousal MAE"), display(fusion_arousal_top)

3 videos with lowest face_arousal MAE

shape: (3, 5)
┌──────────┬──────────────┬──────────────────┬───────────────────┬────────────────────┐
│ video_id ┆ Stablization ┆ mae_face_arousal ┆ mae_scene_arousal ┆ mae_fusion_arousal │
│ ---      ┆ ---          ┆ ---              ┆ ---               ┆ ---                │
│ i64      ┆ bool         ┆ f64              ┆ f64               ┆ f64                │
╞══════════╪══════════════╪══════════════════╪═══════════════════╪════════════════════╡
│ 102      ┆ false        ┆ 0.0015           ┆ 0.2946            ┆ 0.1972             │
│ 95       ┆ false        ┆ 0.0019           ┆ 0.1836            ┆ 0.1089             │
│ 81       ┆ true         ┆ 0.0039           ┆ 0.131             ┆ 0.0939             │
└──────────┴──────────────┴──────────────────┴───────────────────┴────────────────────┘

3 videos with lowest scene_arousal MAE

shape: (3, 5)
┌──────────┬──────────────┬───────────────────┬──────────────────┬────────────────────┐
│ video_id ┆ Stablization ┆ mae_scene_arousal ┆ mae_face_arousal ┆ mae_fusion_arousal │
│ ---      ┆ ---          ┆ ---               ┆ ---              ┆ ---                │
│ i64      ┆ bool         ┆ f64               ┆ f64              ┆ f64                │
╞══════════╪══════════════╪═══════════════════╪══════════════════╪════════════════════╡
│ 79       ┆ false        ┆ 0.0007            ┆ 0.2462           ┆ 0.1131             │
│ 34       ┆ true         ┆ 0.002             ┆ 0.229            ┆ 0.0936             │
│ 96       ┆ true         ┆ 0.0036            ┆ 0.2396           ┆ 0.0934             │
└──────────┴──────────────┴───────────────────┴──────────────────┴────────────────────┘

3 videos with lowest fusion_arousal MAE

shape: (3, 5)
┌──────────┬──────────────┬────────────────────┬───────────────────┬──────────────────┐
│ video_id ┆ Stablization ┆ mae_fusion_arousal ┆ mae_scene_arousal ┆ mae_face_arousal │
│ ---      ┆ ---          ┆ ---                ┆ ---               ┆ ---              │
│ i64      ┆ bool         ┆ f64                ┆ f64               ┆ f64              │
╞══════════╪══════════════╪════════════════════╪═══════════════════╪══════════════════╡
│ 12       ┆ false        ┆ 0.0032             ┆ 0.0947            ┆ 0.1181           │
│ 55       ┆ false        ┆ 0.0044             ┆ 0.1068            ┆ 0.1151           │
│ 114      ┆ true         ┆ 0.0071             ┆ 0.0876            ┆ 0.2166           │
└──────────┴──────────────┴────────────────────┴───────────────────┴──────────────────┘

# Check cols

Uncertainty presented here takes the square root of variance: Gives a standard deviation with the same units as valence/arousal (i.e., you can say “±0.1 valence”), which is easier to contextualize.

In [9]:
res_df.select("video_id", "Stablization", cs.ends_with("std_dev")).sort("video_id")

shape: (248, 4)
┌──────────┬──────────────┬─────────────────┬─────────────────┐
│ video_id ┆ Stablization ┆ valence_std_dev ┆ arousal_std_dev │
│ ---      ┆ ---          ┆ ---             ┆ ---             │
│ i64      ┆ bool         ┆ f64             ┆ f64             │
╞══════════╪══════════════╪═════════════════╪═════════════════╡
│ 0        ┆ false        ┆ 0.019545        ┆ 0.01005         │
│ 0        ┆ true         ┆ 0.020377        ┆ 0.011314        │
│ 1        ┆ false        ┆ 0.018638        ┆ 0.010737        │
│ 1        ┆ true         ┆ 0.020397        ┆ 0.011023        │
│ 2        ┆ false        ┆ 0.030047        ┆ 0.014163        │
│ …        ┆ …            ┆ …               ┆ …               │
│ 121      ┆ true         ┆ 0.007766        ┆ 0.003911        │
│ 122      ┆ false        ┆ 0.017297        ┆ 0.007747        │
│ 122      ┆ true         ┆ 0.017629        ┆ 0.008031        │
│ 123      ┆ false        ┆ 0.015776        ┆ 0.009087        │
│ 123      ┆ true         ┆ 0.019658        ┆ 0.008271        │
└──────────┴──────────────┴─────────────────┴─────────────────┘

In [ ]:
(
    res_df.filter(
        pl.col("face_beats_fusion_valence") == False,
        pl.col("face_beats_fusion_arousal") == False,
        pl.col("scene_beats_fusion_valence") == False,
        pl.col("scene_beats_fusion_arousal") == False,
    )
    .select("video_id", "Stablization", cs.starts_with("mae"))
    .unpivot(
        on=cs.ends_with("valence"),
        index=["video_id", "Stablization"],
        variable_name="valence",
        value_name="mae",
    )
    .sort("video_id", "Stablization")
)

shape: (39, 4)
┌──────────┬──────────────┬────────────────────┬──────────┐
│ video_id ┆ Stablization ┆ valence            ┆ mae      │
│ ---      ┆ ---          ┆ ---                ┆ ---      │
│ i64      ┆ bool         ┆ str                ┆ f64      │
╞══════════╪══════════════╪════════════════════╪══════════╡
│ 9        ┆ false        ┆ mae_scene_valence  ┆ 0.250187 │
│ 9        ┆ false        ┆ mae_fusion_valence ┆ 0.122814 │
│ 9        ┆ false        ┆ mae_face_valence   ┆ 0.193488 │
│ 9        ┆ true         ┆ mae_fusion_valence ┆ 0.092993 │
│ 9        ┆ true         ┆ mae_face_valence   ┆ 0.194132 │
│ …        ┆ …            ┆ …                  ┆ …        │
│ 115      ┆ false        ┆ mae_face_valence   ┆ 0.176396 │
│ 115      ┆ false        ┆ mae_scene_valence  ┆ 0.097148 │
│ 115      ┆ true         ┆ mae_face_valence   ┆ 0.175914 │
│ 115      ┆ true         ┆ mae_fusion_valence ┆ 0.063661 │
│ 115      ┆ true         ┆ mae_scene_valence  ┆ 0.093327 │
└──────────┴──────────────┴────────────────────┴──────────┘

In [ ]:
(
    res_df.filter(pl.col("video_id") == 40)
    .select("video_id", cs.starts_with("mean"), cs.ends_with("std_dev"))
    .with_columns(pl.all().round(3))
    .glimpse()
)

Rows: 2
Columns: 9
$ video_id            <i64> 40, 40
$ mean_scene_valence  <f64> 0.118, 0.133
$ mean_scene_arousal  <f64> -0.061, -0.065
$ mean_face_valence   <f64> -0.123, -0.122
$ mean_face_arousal   <f64> 0.275, 0.273
$ mean_fusion_valence <f64> -0.059, -0.03
$ mean_fusion_arousal <f64> 0.043, 0.038
$ valence_std_dev     <f64> 0.013, 0.012
$ arousal_std_dev     <f64> 0.007, 0.006